### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::11434

### ISSUE THREAD

**Issue by Katchyuser** [Gimer-Studios/APIMyLlama#1]
Hello,

I have installed APIMyLlama on the server where I have Ollama and I am getting the error message regarding port # 11434. 

As a workaround I can use port 11345 but then I will need to disable port 11434 right? 

Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1337:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 11434
}

**Comment by Gimer-Studios** [comment]
What port are you using on Ollama?

**Comment by Gimer-Studios** [comment]
I just added a new feature that allows you to change the port that the Ollama server is running on to your desired one. Just redownload the repository. By default, it is 11434. But just run the 'ollamachangeport <OLLAMA_SERVER_PORT>' and change it to your desired port. If this doesn't fix it, please tell me. This feature should make it so both the Ollama and applications port are customizable.

**Comment by Katchyuser** [comment]
@Gimer-Studios Thank you for the quick response. 
The Ollama server is running on 11434 and I assume we must use the same port for APIMyLlama. 
I am not sure if both Ollama and APIMyLlama will work on same port 11434. I will try out the update and see if it will fix this issue.

**Comment by Gimer-Studios** [comment]
You can not use Ollama and APIMyLlama on the same port. Sorry for the misunderstanding. I will update the documentation now. APIMyLlama can be run on any port but the same one as Ollama.
