### ISSUE TITLE
Error: 404 Client Error: Not Found for url: http://localhost:11434/generate

### ISSUE THREAD

**Issue by melgabay** [Gimer-Studios/APIMyLlama#3]
I’m encountering a `404 Client Error: Not Found for url` when trying to send a POST request to the `/generate` endpoint of the APIMyLlama API. 

**Steps to Reproduce:**

1. Set up the APIMyLlama server according to the instructions.
2. Start the server using `node APIMyLlama.js` and generated a key:

```Connected to the apiKeys.db database.
Server running on port 5001
generatekey
API key generated: aa4f00fb55849c9932d6c4126f238313ea7ba071
> generatekey
API key generated: ****************************************
```

3. Send a POST request to `http://localhost:11434/generate` using the following Python Flask code:

```
from flask import Flask, request, jsonify, render_template
import requests

app = Flask(__name__)

API_KEY = 'API_KEY_I_RECEIVE_FROM_APIMyLlama.js'

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/chat', methods=['POST'])
def chat():
    data = request.json
    prompt = data.get('prompt')

    try:
        print(f"Sending request to APIMyLlama with prompt: {prompt}")
        response = requests.post('http://localhost:11434/generate', json={
            'apikey': API_KEY,
            'prompt': prompt,
            'model': 'llama3',
            'stream': True
        })
        print(f"Response received: {response.status_code}, {response.text}")

        response.raise_for_status()
        return jsonify(response.json())
    except requests.exceptions.RequestException as e:
        print(f"Error during request: {e}")
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True)
```

 HTML CODE:

```
<!DOCTYPE html>
<html>
<head>
    <title>Chat avec Ollama</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        #chat-box {
            width: 80%;
            max-width: 600px;
            height: 400px;
            border: 1px solid #ccc;
            padding: 10px;
            overflow-y: scroll;
            margin: 0 auto 20px;
        }
        .message {
            padding: 10px;
            margin: 5px 0;
            border-radius: 5px;
        }
        .user {
            background-color: #e0f7fa;
            text-align: right;
        }
        .bot {
            background-color: #ffeb3b;
            text-align: left;
        }
    </style>
</head>
<body>
    <div id="chat-box"></div>
    <input type="text" id="chat-input" placeholder="Type your message here...">
    <button onclick="sendMessage()">Send</button>

    <script>
        async function sendMessage() {
            const input = document.getElementById('chat-input');
            const message = input.value;
            input.value = '';

            const chatBox = document.getElementById('chat-box');
            const userMessage = document.createElement('div');
            userMessage.className = 'message user';
            userMessage.innerText = message;
            chatBox.appendChild(userMessage);

            const response = await fetch('/chat', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ prompt: message })
            });

            const data = await response.json();
            const botMessage = document.createElement('div');
            botMessage.className = 'message bot';
            botMessage.innerText = data.response || 'Error: ' + data.error;
            chatBox.appendChild(botMessage);

            chatBox.scrollTop = chatBox.scrollHeight;
        }
    </script>
</body>
</html>
```

**Expected Result:**

The server should return on my terminal that all is good but I receive
```
Sending request to APIMyLlama with prompt: hey
Response received: 404, 404 page not found
Error during request: 404 Client Error: Not Found for url: http://localhost:11434/generate
127.0.0.1 - - [31/Jul/2024 17:12:21] "POST /chat HTTP/1.1" 500 -
```

**Actual Result:**
<img width="1137" alt="Capture d’écran 2024-07-31 à 17 26 00" src="https://github.com/user-attachments/assets/6837d2d1-bb52-4171-a02f-3c18bc0afa7e">

The response is a `404 Client Error: Not Found` indicating that the `/generate` endpoint does not exist or is incorrectly specified.

**Additional Information:**

- The server is running and responds with "Ollama is running" when accessing `http://localhost:11434` via `curl`.
- I’ve double-checked the API key and endpoint URL.
- Documentation and examples provided with APIMyLlama suggest using `/generate` but the endpoint seems to be unresponsive or incorrect.

**Questions:**

1. Is `/generate` the correct endpoint for APIMyLlama, or has it been updated?
2. Are there any specific configurations or additional steps required to make this endpoint available to get an answer from Ollama?

**Comment by Gimer-Studios** [comment]
I see the problem. I believe it's with your port. See when you setup APIMyLlama on first installation. It asks for you Ollama Server port and your API server port. You are supposed to use the API port not the Ollama Server port.

PS C:\Users\reddy\Downloads\APIMyLlama-main> node APIMyLlama.js
APIMyLlama V2 is being started. Thanks for choosing Gimer Studios.
Connected to the apiKeys.db database.
Enter the port number for the API server: 3000
Port number saved to port.conf: 3000
Enter the port number for the Ollama server (Port that your Ollama server is running on. By default it is 11434 so if you didnt change anything it should be that.): 11434
Ollama port number saved to ollamaPort.conf: 11434
Server running on port 3000

As shown in the example above you would use port 3000 in this case not 11434. So, when you start up APIMyLlama in the terminal. When it says, "Server running on port " Thats the port you need to use. Like mentioned in the documentation the API port and the Ollama port are 2 different things.

**Comment by Gimer-Studios** [comment]
So, in your code instead of 

Original:

        print(f"Sending request to APIMyLlama with prompt: {prompt}")
        response = requests.post('http://localhost:11434/generate', json={
            'apikey': API_KEY,
            'prompt': prompt,
            'model': 'llama3',
            'stream': True
        })
        
Updated (API Port would be whatever you set it to on startup):

                print(f"Sending request to APIMyLlama with prompt: {prompt}")
        response = requests.post('http://localhost:<API_PORT>/generate', json={
            'apikey': API_KEY,
            'prompt': prompt,
            'model': 'llama3',
            'stream': True
        })
